### ISSUE TITLE
Dataset creation doesn't allow empty labels

### ISSUE THREAD

**Issue by gammasts** [emedvedev/attention-ocr#100]
Looks like the change from https://github.com/emedvedev/attention-ocr/commit/0cfeacb945f78e810ebac587ab06a67e7da9d752 broke allowing empty labels due to the behavior of `.split(None, 1)`. The split consumes all whitespace in between non-whitespace characters, so having entries like below end up throwing an exception since the split only returns one value. Even with `\t` (the original behavior), it collapses various types of whitespace and skips the entry, so this also breaks labels that are a single space, as well as labels preceeded by whitespace.

```
/tmp/dataset/test_1.png this is a test
/tmp/dataset/test_2.png 
/tmp/dataset/test_3.png something
/tmp/dataset/test_4.png  preceeded by a space
```

**Comment by emedvedev** [comment]
Ah, that makes sense. Would you mind submitting a PR for this?

**Comment by gammasts** [comment]
You're too quick in replying, was typing it up :)
