### ISSUE TITLE
What is "target embedding size"

### ISSUE THREAD

**Issue by Rayndell** [emedvedev/attention-ocr#103]
Hello again, I have a question regarding the parameter "target embedding size", I was not able to understand what it means exactly. Do we have a chance to improve the model by modifying this value?

**Comment by emedvedev** [comment]
Yes, you can definitely try to fine-tune it (increasing the embedding size might give you better results in some cases). Here's a good explanation: [https://stackoverflow.com/questions/40784656/tf-contrib-layers-embed-sequence-is-for-what/44280918#44280918](https://stackoverflow.com/questions/40784656/tf-contrib-layers-embed-sequence-is-for-what/44280918#44280918).
