### ISSUE TITLE
Advantage to converting data to upper case?

### ISSUE THREAD

**Issue by kulkarnivishal** [emedvedev/attention-ocr#104]
Hi @emedvedev, 

Is there an advantage to force the dataset to uppercase rather than having separate classes for upper and lower case? I think that the accuracy is hurting for having to map two classes two one? I would train with no-force-uppercase but I have been training Synth90k with default parameters for over a month and wanted your advice before retraining. 

Best regards,
Vishal

**Comment by emedvedev** [comment]
It might turn out than no-force-uppercase would indeed be better than the default when in comes to Synth90k, but I can't predict by how much :) 

Note that the fonts and distortions in Synth90k images are already varied enough that it's not quite as simple as "two classes" for uppercase and lowercase though. Even if you get improved accuracy, don't expect a very significant improvement. Wouldn't hurt to try though!

**Comment by kulkarnivishal** [comment]
Thank you so much. I will try training in google CloudML with multi-gpu.

**Comment by kulkarnivishal** [comment]
Hi, 

The code currently doesn't support training with multi-gpu, does it? Any direction to how I can get it implemented would be much appreciated. 

Best regards,
Vishal

**Comment by emedvedev** [comment]
It does not, and unfortunately I don't have any experience with multi-gpu training, so you're on your own. :)

I'm going to close this issue, because the original problem has been addressed, but feel free to open a new one if you run into problems with the codebase.
