### ISSUE TITLE
ValueError: '\xe2' is not in list error when i try to train with color parameter

### ISSUE THREAD

**Issue by kulkarnivishal** [emedvedev/attention-ocr#110]
Hi @emedvedev 

I get this error after a first few steps when I train with --color parameter (set channels to 3). Could you please help? 
Please find the error log below:
![image](https://user-images.githubusercontent.com/36867201/45266055-f866eb80-b409-11e8-992c-714e0b361332.png)

**Comment by emedvedev** [comment]
This error means that your image labels have a character that's not in the model charmap. Check your labels, because by default the supported charset is numbers + uppercase only: https://github.com/emedvedev/attention-ocr/blob/7bb17af211de60e0fff5d56925f73d9018def744/aocr/util/data_gen.py#L23.

**Comment by kulkarnivishal** [comment]
Thank you for the prompt response. I used --full-ascii and --no-force-uppercase flags as well, I assumed --full-ascii covers all characters. Am I missing something?

**Comment by emedvedev** [comment]
`--full-ascii` covers the ASCII range (uppercase, lowercase, symbols, etc.). There's no flag for covering the entire Unicode range, and you'd have to manually modify the CHARMAP (at the line I've mentioned before). Not sure about the performance in that case though—you might have to consider modifying the dataset labels unless Unicode plays significant part in it.

**Comment by kulkarnivishal** [comment]
thank you for the reply. I am able to train the model. However, I now see a very weird issue. I added synthetic images (generated using GANs) to the training data, and few cropped COCO images. So about 1M synthetic images and Synth90k and about 60k coco images. The training loss is improving but when I test the model for prediction, it performs very poorly. It just prints "cccc" or "aaaaa" etc. 
Am I doing something wrong? 

Here's the training log:
![image](https://user-images.githubusercontent.com/36867201/45722080-a0458d00-bb5f-11e8-9187-b5671fadf6e3.png)

**Comment by aosetrov** [comment]
Hi @kulkarnivishal ,
Did you manage to solve this problem?
If yes, please share a hint)

**Comment by kulkarnivishal** [comment]
Not really. Although, I continued the training for 3 more weeks and results look better, not that great though. The main issue I am facing is predicting symbols. No matter how I train the inference seems to be getting it always wrong.

**Comment by aosetrov** [comment]
You can try to manually change the dictionary instead of using keys. At the same time I have no idea how you managed to add a non-ASCII labeled targets to the train-set .tfrecords file. When I tried to do this it used to throw an error of encoding all the time(

**Comment by kulkarnivishal** [comment]
you mean manually adding symbols instead of using full-ascii flag? 
And I used python's string.printable to filter non-ascii characters

**Comment by kspook** [comment]
@emedvedev , I han an error even though I chaned as you mentioned.
(@kulkarnivishal, how did you change?)
*error message.
`ValueError: '!' is not in list`

* changed code
`DataGen.CHARMAP = ['', '', ''] + list('!#$%&()*+-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ?@')`

> This error means that your image labels have a character that's not in the model charmap. Check your labels, because by default the supported charset is numbers + uppercase only: 
>   
>     
>       attention-ocr/aocr/util/data_gen.py
>     
>     
>          Line 23
>       in
>       7bb17af
>     
>     
>     
>     
> 
>         
>           
>            CHARMAP = ['', '', ''] + list('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ') 
>         
>     
>   
> 
> .

**Comment by kspook** [comment]
> This error means that your image labels have a character that's not in the model charmap. Check your labels, because by default the supported charset is numbers + uppercase only: 
>   
>     
>       attention-ocr/aocr/util/data_gen.py
>     
>     
>          Line 23
>       in
>       7bb17af
>     
>     
>     
>     
> 
>         
>           
>            CHARMAP = ['', '', ''] + list('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ') 
>         
>     
>   
> 
> .

**Comment by kspook** [comment]
@emedvedev , in my case, aocr doesn't look to catch changed code.

I nn defaults.py, I changed max_prediction 8 to 18. but it still show 8.

![image](https://user-images.githubusercontent.com/36400753/60166178-9dd53980-983b-11e9-8e59-44a6dae08eb9.png)
