### ISSUE TITLE
Training progress stop at step 0 unexpectedly

### ISSUE THREAD

**Issue by trananhdung17** [emedvedev/attention-ocr#112]
I have an issue when tried to train my dataset. Training progress stop at step 0 without any kill-signal.
aocr version is 0.7.5
Tensorflow version is 1.8
OS Ubuntu 16.04
The command i ran:
```
# aocr train training.tfrecords --initial-learning-rate 0.1 --max-height 160
```

and tried some:
```
# aocr train training.tfrecords --initial-learning-rate 0.1
# aocr train training.tfrecords
```
got same results.

Here is console log:
![aocr_issue](https://user-images.githubusercontent.com/10810900/46076990-7e7c8380-c1b9-11e8-8306-02dc30cd6ccb.JPG)

**Comment by emedvedev** [comment]
It usually means that your dataset wasn't enough to make even a single step: maybe it was too small, maybe all the images were skipped, etc. I would look at that direction.

**Comment by trananhdung17** [comment]
My dataset contain 26 x 400 image (400 png file for A -> Z Latin character) with size 278x278 for each image.
Could you advise me about parameters for training with my dataset.
Or if my dataset is not enough, pls let me know recommended dataset size.
Thank you so much!

**Comment by emedvedev** [comment]
Unfortunately, I don't have any time to advise on datasets, so this issue tracker is limited to bugs and issues in code only.

I would recommend you to debug the `step` method and see why it doesn't do any actual training. My best bet is that something in your dataset is causing all images to be skipped.
