### ISSUE TITLE
Implement aocr on a limited data

### ISSUE THREAD

**Issue by ATS-Official** [emedvedev/attention-ocr#115]
I am trying to implement aocr for digital multimeter readings and the image will be taken in a unconstrained env and needed attention based OCR. I dont have the luxury of a large dataset and trying to play around with available data and not able to get desired accuracy.
Few questions could you please answer;
1. During training with input data is there a parameters option to use pre-trained models like inception (aocr train ./train/train.tfrecords -- checkpoint??) ?
2. It shows like test model works independently "aocr test --visualize ./test/test.tfrecords"
, shouldn't be the model testing should refer already trained model check points as parameter?.

**Comment by emedvedev** [comment]
1. You can't use inception (or any other pre-trained models), because aocr isn't just a tool, it's also a model.
2. There's a `--model-dir` parameter which defaults to `./checkpoints`. You can specify any other directory, of course.
