### ISSUE TITLE
Missing test on over 500 images, help!

### ISSUE THREAD

**Issue by kulkarnivishal** [emedvedev/attention-ocr#121]
Hi @emedvedev 

I have 2534 images in total for testing, and while inspecting the generated tfrecords I could see 2534 images as well 
![image](https://user-images.githubusercontent.com/36867201/48797846-22654580-ecb8-11e8-8612-b2ce9014e6f3.png)

But when I test these images the, code logs only 1980 steps. I checked whether any images are being skipped in data_gen.py but that is not that case either. Could you help, where might the issue be?
![image](https://user-images.githubusercontent.com/36867201/48797958-65271d80-ecb8-11e8-9cd5-c7ba0d30996f.png)

Looking forward to your reply. 

Best,
Vishal

**Comment by docastage** [comment]
The default max-width is 160. You might have to include max-width and max-height parameters in order to include all the images. I faced the same issue and adding these two parameters solved it.

**Comment by kulkarnivishal** [comment]
Thank you, I figured it out. Well, ideally shouldn't the image be resized to max-height * max-width as a pre-processing step? I have noticed that there's no proper logging in data_gen.py as well.
