### ISSUE TITLE
Prediction repeats character

### ISSUE THREAD

**Issue by mllearner96** [emedvedev/attention-ocr#123]
Thank you very much for the brilliant package. As you can see in the following text output and image, characters are predicted twice. Beside this problem, the prediction seems to be very accurate. My training data includes around 3000 images. Is the training data too small or do I need to tune something?

```
BAATU33
BATU 3
```
![image](https://user-images.githubusercontent.com/46249200/50541746-08caee00-0bd4-11e9-972c-45e4d1a748e8.gif)

**Comment by emedvedev** [comment]
I don't think the training dataset is too small, but you may need more training epochs or indeed some hyperparameter tuning. Unfortunately, I don't have the capacity to debug training/dataset issues, unless it's a problem with the codebase, but wish you best of luck! Looks like you're pretty close :)
