### ISSUE TITLE
training parameter on Synth 90k

### ISSUE THREAD

**Issue by roger12337** [emedvedev/attention-ocr#125]
What is the optimal training parameters for Synth 90k? When does it converge?

**Comment by emedvedev** [comment]
[The defaults](https://github.com/emedvedev/attention-ocr/blob/master/aocr/defaults.py) are fairly optimal, except you might want to increase the batch size (to something like 20) and decrease the number of epochs.

Make sure you adjust `max-width`, `max-height`, and `max-prediction`, too.
