### ISSUE TITLE
Parameters are changed when testing

### ISSUE THREAD

**Issue by roger12337** [emedvedev/attention-ocr#127]
Don't know whether you have faced similar situation. After I have trained model (perplexity = 1.1), I do some testing on other images. After I continue to train the model with the same data, parameters are quite different and has perplexity of 5. Does anyone know why this occurs?

**Comment by roger12337** [comment]
I explore a little more. The performance of the model is consistent when both training and testing data has same max-width and max-height.

**Comment by emedvedev** [comment]
That would make sense. Good accuracy with images of different sizes would require a large and extensive dataset, and if your testing data has image sizes that are completely different from training, you won't see good results. 

I'll close the issue for now, but if there's any issues with the model itself, do let me know!
