### ISSUE TITLE
time taken for ocr is too long

### ISSUE THREAD

**Issue by pp3993** [emedvedev/attention-ocr#128]
Hi,
Thanks for the repo, i used this toolkit for the ocr of my own data(size of one of the image is 143*37) and the time taken for the ocr of jpg image is 8 secs. Moreover, if i run this on full image this gonna take to much time. while on tfrecords of the images this took around 0.05 secs. only

the script used for the ocr is :
frozen_model_filename = "/path/to/model/exported-model/frozen_graph.pb"

config = tf.ConfigProto(allow_soft_placement=True)
sess = tf.Session(config=config)
with tf.gfile.GFile(frozen_model_filename, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')
sess.run(tf.global_variables_initializer())

x = sess.graph.get_tensor_by_name('input_image_as_bytes:0')
y = sess.graph.get_tensor_by_name('prediction:0')
allProbs = sess.graph.get_tensor_by_name('probability:0')

def getImage(path):
    with open(path, 'rb') as img_file:
        img = img_file.read()

    return img

img=getImage('/path/to/Images/xxx_71800_1.jpg')
(y_out, probs_output) = sess.run([y,allProbs], feed_dict={x: [img]})
       

Any idea why it is taking long time for ocr of small image?

**Comment by emedvedev** [comment]
Most likely it's the Tensorflow launch and the model import that's taking so long, not the OCR process itself. Ideally, you'd run the predictions as a service, not as a script, so that the initialization only happens once. 8 seconds is certainly a lot of time though, so you might want to time different steps and see if there's something you could optimize.

**Comment by pp3993** [comment]
Hi,
thanks for the quick reply. the time taken for OCR process itself is so long. not the model import.

start=time.time() 
(y_out, probs_output) = sess.run([y,allProbs], feed_dict={
            x: [img]
        })
end=time.time()
print(y_out)
print('time',end-start)

time 6.485961437225342

**Comment by emedvedev** [comment]
If you run the same prediction twice in a row, would the first time be any different from the second?

**Comment by pp3993** [comment]
yeah, for the first run it took long time while for the second time just 0.07 secs only.
thanks.
