### ISSUE TITLE
How can I generate tfrecord files?

### ISSUE THREAD

**Issue by rsierrap** [emedvedev/attention-ocr#142]
Hi, I would like training a model to recognize a custom dataset. However, I have a problem building the tfrecord file. I have no idea to do this. Please, can anyone tell me step by step how can I generate the tfrecord files???

**Comment by emedvedev** [comment]
I think the ["create a dataset" section of the README.md](https://github.com/emedvedev/attention-ocr/#create-a-dataset) covers it reasonably well.

**Comment by rsierrap** [comment]
More or less, but I create a similar dataset and the train process does not work. It never cross the zero step.

**Comment by emedvedev** [comment]
Make sure `max-width` and `max-height` are set correctly during training. It’s possible the default values are too low and your entire dataset gets skipped.

**Comment by princeverma03** [comment]
Can we train with multiple tf record files (shards). If so , how?
