### ISSUE TITLE
ValueError: ' ' is not in list

### ISSUE THREAD

**Issue by mjack3** [emedvedev/attention-ocr#143]
I'm training my own dataset. Here there is my actual alphabet from 

CHARMAP = ['', '', ''] + list("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,.-! ")

note my alphabet it has a space lane at the end because cmd return me the next message

ValueError: ' ' is not in list

any help would be great as its for an urgent project. Thanks all!

**Comment by mjack3** [comment]
Actually i have found that this message changes, sometimes says ' ' is not in list, '.' is not in list.....
But you can check it exists  in my before character list

**Comment by mjack3** [comment]
I tryed with FULL_ASCII = True but it's not work.

And somes times in getting assert len(lex) < self.bucket_specs[-1][1].
I configured the next parameters MAX_PREDICTION = 20 but actually havent words with that size. Something is going wrong i think :S

**Comment by mjack3** [comment]
I will attach a screenshot of my problems.

Here what the cmd return
https://pasteboard.co/IoFcXoa.png

Here my data_gen.py
https://pasteboard.co/IoFe3z1.png

**Comment by mjack3** [comment]
fixed, i was ritting in the wrong place

**Comment by smoolya17** [comment]
I am curious how
`CHARMAP = ['', '', ''] + list("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,.-! ")`
is wrong?

**Comment by mjack3** [comment]
I was writing in an incorrect file :)

**Comment by VikramBharadwaj1995** [comment]
Hey, how did you fix this issue?
