### ISSUE TITLE
InvalidArgumentError (see above for traceback): Cannot assign a device for operation prefix/Rank: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.

### ISSUE THREAD

**Issue by AhmadShaik** [emedvedev/attention-ocr#146]
When I tried to perform prediction on a single image, I am getting an error at Node prefix/Rank: saying could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
I am trying to solve this problem from quite a long time. Any help or suggestions are appreciated.

**Comment by chhatrachhorm** [comment]
I believe you can fix this by passing the argument `--gpu-id -1`.
e.g. `aocr train ./datasets/training.tfrecords --gpu-id -1` this will let the code to use `cpu:0` instead.
see this [model.py#L60](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L60) and this [\_\_main\_\_.py#L88](https://github.com/emedvedev/attention-ocr/blob/master/aocr/__main__.py#L88)

**Comment by Ryansanity** [comment]
> I believe you can fix this by passing the argument `--gpu-id -1`.
> e.g. `aocr train ./datasets/training.tfrecords --gpu-id -1` this will let the code to use `cpu:0` instead.
> see this [model.py#L60](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L60) and this [__main__.py#L88](https://github.com/emedvedev/attention-ocr/blob/master/aocr/__main__.py#L88)

i got the same question,need help~.~
