### ISSUE TITLE
Option to add custom character vocabulary

### ISSUE THREAD

**Issue by ashwath98** [emedvedev/attention-ocr#159]
I think that it will be useful to have an additional parameter where the user can add their own character set for the model.

I think this can be done with some changes to the data_gen code to take characters from a file, and a custom_vocab parameter.

Do you think I should go ahead with implementing this?

**Comment by emedvedev** [comment]
Of course! I’ll gladly accept a PR. If you look into closed issues, we did have people training with non-standard charsets, and they still might have code patches left.

**Comment by ashwath98** [comment]
Great!! Thanks
