### ISSUE TITLE
some string issues with python3, especially --visualize

### ISSUE THREAD

**Issue by ckirmse** [emedvedev/attention-ocr#16]
Hi--this is a great repo, thanks to the original authors and the great work you have done to make it more usable.

With the very latest code (I pulled on morning of oct-7-2017), there are a few string issues. The 'test' command is reporting incorrect results due to some byte / string issue, even if the prediction is correct. I'm seeing things like b"B'test'" vs b'test (where the correct word is test), and the extra b and quotes are reducing the reported quality of the results. I have a hack to work around it but I'm just learning my way around this code so you might have a better answer.

Similarly, --visualize doesn't work at all because the "filename" being passed in isn't actually a string, but a byte literal.

Separately I tried to run this under python2 at first and there was some issue with that too.

Anyway, if you have fixes, please go ahead, or if you have suggestions on the best way you want it fixed, I'll proceed and send in a PR.

**Comment by emedvedev** [comment]
Hi! There was a recent PR with some python3 fixes, and my subsequent fixes later: https://github.com/emedvedev/attention-ocr/commit/d299c507851132cf86fd1364a94388c109aea935 and https://github.com/emedvedev/attention-ocr/commit/44bb58ed5403d4479398af985be08eb06e649479. This must be what've caused the issue, although I tested training and exporting after merging, and it was fine—although I can imagine that my testing just wasn't thorough enough.

I would greatly appreciate a PR, and the issue must be in the two commits I mentioned above somewhere. If you need more pointers, please let me know.

**Comment by reidjohnson** [comment]
Hey all, I ran into this issue as well. It seems some byte-encoded variables are expected as strings. I'm not sure that it's the most principled approach, but converting the model output ([line 270 of model.py](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L270)) and label input ([line 59 of data_gen.py](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/data_gen.py#L59)) to strings with 'utf-8' encodings (e.g., `output = str(output, 'utf-8')`) seemed to resolve the issue for me with Python 3.

**Comment by ckirmse** [comment]
fix was merged
