### ISSUE TITLE
Space prediction

### ISSUE THREAD

**Issue by vladdders** [emedvedev/attention-ocr#160]
Hello,

Say I want to predict an image that contains 2 words with a space between them, something like: 'ABC 1234'. Is attention ocr able to do such prediction? I have tried to generate such sequences and train but I haven't been able to obtain decent results... I am not entirely sure how to store the lables in the txt files considering it has a space, should I use quotation marks? But then is it able to disregard that character and not consider it as part of the label?

Regards, 
Vlad

**Comment by emedvedev** [comment]
Just treat space as any other character, IIRC it should still work.

**Comment by vladdders** [comment]
It is possible to do this by using the the `--full-ascii` argument in the training command.

**Comment by laksh9950** [comment]
> It is possible to do this by using the the `--full-ascii` argument in the training command.

is it working by using --full-ascii are you getting spaces in your prediction

**Comment by vladdders** [comment]
Yes, what that does is adding all the ascii characters, including `' '` to your charmap.

**Comment by laksh9950** [comment]
thanks  i am doing the same training
how your accuracy coming 
how did you create a dataset with multiple words

**Comment by laksh9950** [comment]
> Yes, what that does is adding all the ascii characters, including `' '` to your charmap.
thanks i am doing the same training
how your accuracy coming
how did you create a dataset with multiple words

**Comment by laksh9950** [comment]
> Yes, what that does is adding all the ascii characters, including `' '` to your charmap.

How did you created the dataset of multiple words
Can you share training hyperparameters
