### ISSUE TITLE
Documentation for input/output tensors

### ISSUE THREAD

**Issue by thhart** [emedvedev/attention-ocr#162]
I want to integrate the model programmatically, how to receive more detailed information from the output model. How are the tensors named and structured in the graph to receive information like this (if available):

**input:**

image data bytes

**output:**

bounding box location
score/probability
single character location

**Comment by maxpaynestory** [comment]
Also interested to know about output tensors.

**Comment by maxpaynestory** [comment]
I guess the output tensors are

probability
output

taken from tensorflow model server rest api results.

**Comment by maxpaynestory** [comment]
Here is what people are using

```python
image_tensor = detection_graph.get_tensor_by_name('input_image_as_bytes:0')
prediction_result = detection_graph.get_tensor_by_name('prediction:0')
allProbs = detection_graph.get_tensor_by_name('probability:0')
```
