### ISSUE TITLE
Converting to frozen graph

### ISSUE THREAD

**Issue by themechanicalcoder** [emedvedev/attention-ocr#168]
I have downloaded and extracted the model from the original GitHub repository. Please explain how to convert it to a frozen graph format. Here is how the extracted directory looks like.
![image](https://user-images.githubusercontent.com/34737471/75741405-80446200-5d30-11ea-8eef-5d5911d19d06.png)
 What are the changes that I need to make in the [export code ](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/export.py) code to convert to frozen-graph?.

**Comment by maxpaynestory** [comment]
create a new folder exported-model

and run

```
aocr export --format=frozengraph ./exported-model
```
