### ISSUE TITLE
test --visualize doesn't work

### ISSUE THREAD

**Issue by ckirmse** [emedvedev/attention-ocr#18]
Entering this as a to-do item. It looks like it broke in the conversion to use TFRecordDataset

To fix, I think the proper solution is to:
- add filename into the record in dataset.py:generate
- read and set filename in data_gen.py:_parse_record
- pass filename into bucket_data.append and save it in there 
- grab filename from batch data in model.py:test and pass it to visualize_attention()

I'm not planning to do this in the next few days so I wanted to put the plan here. If no one else fixes this, hopefully I will soon.

**Comment by emedvedev** [comment]
Thanks for the issue! I don't think we even need a file name, since we can just use the `label` field for that: pass the label (grounds) to `visualize_attention` and created a folder based on the label. If there's more than one file with the same label (like in Synth90k; I think they have the same filename, too), check if the folder already exists and create a folder named `label-<N>`.

That would be a cleaner approach that wouldn't lead to extra fields anywhere, I think.

**Comment by ckirmse** [comment]
That's true, I think that's a better strategy.

**Comment by emedvedev** [comment]
Sweet. I'll see if I can get to it in the next couple weeks, but if not, please feel free to submit a PR!

**Comment by rishikelltontech** [comment]
Hi,
I am also facing the same issue.
test --visualize is not working. When I ran "aocr test --visualize ./datasets/testing.tfrecords", code inside the [for loop](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L257) is not executing. After debugging, I found out that list(self.s_gen.gen(1)) is empty. 

Does anyone have a fix for this?

**Comment by ckirmse** [comment]
@rishikelltontech no, it doesn't currently work--see above on a plan to fix it. If you can do it and make a PR, please do it, otherwise someone else may get to it soon.

**Comment by rishikelltontech** [comment]
@ckirmse : Thanks for the reply. When I run "aocr test --visualize ./datasets/testing.tfrecords", **list(self.s_gen.gen(1))** is empty list. Do you have any idea why it is ging me empty list?

**Comment by ckirmse** [comment]
No, that doesn't make sense if you successfully made a testing.tfrecords file. Try rebuilding it with the latest code, which has some extra safety checks.
