### ISSUE TITLE
given num-epoch 200 but the training is continuing Step 328+, for how many steps it will continue?

### ISSUE THREAD

**Issue by anidiatm41** [emedvedev/attention-ocr#194]
aocr train ./data/training.tfrecords --max-width 200 --max-height 100 --model-dir ./checkpoint --max-prediction 236 --num-epoch 200

**Comment by akiradavid27** [comment]
Hi, I think I figured out the answer to this issue. There is this formula I found in stackoverflow:

(Number of images) / (Number of images per batch / step) = Number of steps per epoch

For example, in my case I used 3000 images, a batch-size of 50 and an epoch of 100. Using the formula I calculated 6,000 steps, which at the end  was the true total amount of steps the model lasted training. 
Hope it helps.
