### ISSUE TITLE
Poor results using exported model in some cases

### ISSUE THREAD

**Issue by ckirmse** [emedvedev/attention-ocr#25]
I'm wondering if anyone else is seeing this.

I have a model trained with 20,000 synthesized images of between 1 and 50 characters, including spaces. Using the 'test' function, I'm getting good results--test images that have short text are usually 100%, and longer ones are usually off by just a character or two. So far so good.

I used the export function and ran the tensorflow_model_server, and then used a little python client to connect to it. With the same test images that I know the model can predict well, I'm seeing terrible results--the first 2-6 characters are usually right, but then almost complete gibberish.

Is anyone else using TensorFlow Serving, and if so, can you report how well it's working? If you're not using it, what are you doing instead? I figure I'll just make a little python wrapper around the "test" function (essentially) that I can communicate with from the rest of my system, but I'd prefer to use TensorFlow Serving if possible because it's one less thing for me to worry about.

**Comment by emedvedev** [comment]
I'll look into it, there's clearly something wrong with exporting. If you export a frozen graph instead of a SavedModel, does it perform any better?

**Comment by ckirmse** [comment]
Ah, that was my next thought too. I exported a frozen graph and have the same exact problem, so it seems to not be related to tensorflow serving, but instead to exporting. I noticed that the frozen graph seems to be too small (data file is 94MiB, meta file is 23MiB, but frozen graph pb is only 32MiB), if I understand that properly.

**Comment by emedvedev** [comment]
Thanks! Looks like a problem with exporting indeed, I'll see what I can do.

**Comment by mattfeury** [comment]
i haven't tried any of the exporting in the codebase as of yet, but prior to it being implemented i was using this script to create a frozen model:

```py
import os, argparse

import tensorflow as tf
from tensorflow.python.framework import graph_util

dir(tf.contrib)
dir = os.path.dirname(os.path.realpath(__file__))

def freeze_graph(model_folder):
    # We retrieve our checkpoint fullpath
    checkpoint = tf.train.get_checkpoint_state(model_folder)
    input_checkpoint = checkpoint.model_checkpoint_path

    # We precise the file fullname of our freezed graph
    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/frozen_model.pb"

    # Before exporting our graph, we need to precise what is our output node
    # This is how TF decides what part of the Graph he has to keep and what part it can dump
    # NOTE: this variable is plural, because you can have multiple output nodes
    output_node_names = "cond_1/Merge"

    # We clear devices to allow TensorFlow to control on which device it will load operations
    clear_devices = True

    # We import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)

    # We retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    for op in graph.get_operations():
        print(op.name)

    # We start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)

        # We use a built-in TF helper to export variables to constants
        output_graph_def = graph_util.convert_variables_to_constants(
            sess, # The session is used to retrieve the weights
            input_graph_def, # The graph_def is used to retrieve the nodes
            output_node_names.split(",") # The output node names are used to select the usefull nodes
        )

        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_folder", type=str, help="Model folder to export")
    args = parser.parse_args()

    freeze_graph(args.model_folder)

```

lifted most of that from here: https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by emedvedev** [comment]
That's pretty much what I've based the frozen graph exporting as well. SavedModel is a bit more tricky, but if the problem appears in both cases, should be something in the shared code.

**Comment by ckirmse** [comment]
@mattfeury were you able to successfully reimport that frozen model and use it? If so, was that within python code or some other system, and can you give an idea of the size of your checkpoint data, meta data, and frozen model? I'm not sure what "normal" is. Thanks!

**Comment by mattfeury** [comment]
yea i was. in fact i just finished getting it going in a TF serving environment and am seeing solid (albeit early) results. i'll share my process below, but as i mentioned earlier, i haven't used any of the new "export" code for any of this as i started working on it prior to that being merged. once i stop being lazy, i'd like to consolidate that obviously.

- so i run that script above to get a frozen_model.pb
- i then was able to verify that worked fine by running a little `predict.py` script i wrote, abbreviated below.
- once i verified that that was groovy, i found a little script to convert the frozen_model.pb to a SavedModel (code below as well).
- i was then able to serve the savedmodel via tf serving in combination with a few other models i'm using. literally just got it running so i'm fairly pleased thus far but i'm sure i'll quickly encounter some issues ;)

also note that you may seem some "probability" stuff in my code, since i'm simultaneously working on #19 

predict.py:
```python
import argparse
import tensorflow as tf
import numpy as np

def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we can use again a convenient built-in function to import a graph_def into the
    # current default Graph
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(
            graph_def,
            input_map=None,
            return_elements=None,
            name="prefix",
            op_dict=None,
            producer_op_list=None
        )
    return graph

def getImage(path):
    with open(path, 'rb') as img_file:
        img = img_file.read()

    return img

frozen_model_filename = "checkpoints/frozen_model.pb"
graph = load_graph(frozen_model_filename)

def ocrImage(image):
    x = graph.get_tensor_by_name('prefix/input_image_as_bytes:0')
    y = graph.get_tensor_by_name('prefix/prediction:0')
    allProbs = graph.get_tensor_by_name('prefix/probability:0')

    img = getImage(image)

    with tf.Session(graph=graph) as sess:
        (y_out, probs_output) = sess.run([y,allProbs], feed_dict={
            x: [img]
        })
        # print(y_out)
        # print(allProbsToScore(probs_output))

        return {
            "predictions": [{
                "ocr": str(y_out),
                "confidence": probs_output
            }]
        };

if __name__ == '__main__':
    # Let's allow the user to pass the filename as an argument
    parser = argparse.ArgumentParser()
    # parser.add_argument("--frozen_model_filename", default="checkpoints_pruned/frozen_model.pb", type=str, help="Frozen model file to import")
    parser.add_argument("--image", default="dfbe0634-ad30-4073-bd56-82b3f5ea524c.jpg", type=str, help="Path to image")
    args = parser.parse_args()
    predictions = ocrImage(args.image)
    print(str(predictions))
```

convert-frozenmodel-to-savedmodel.py
```python
import tensorflow as tf
from tensorflow.python.saved_model import signature_constants
from tensorflow.python.saved_model import tag_constants

export_dir = './graph/saved_model/0001' #this dir can't exist or tf will bitch
graph_pb = 'checkpoints/frozen_model.pb'

builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

with tf.gfile.GFile(graph_pb, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

sigs = {}

with tf.Session(graph=tf.Graph()) as sess:
    tf.import_graph_def(
        graph_def,
        input_map=None,
        return_elements=None,
        op_dict=None,
        name="",
        producer_op_list=None
    )

    g = tf.get_default_graph()

    builder.add_meta_graph_and_variables(
        sess,
        ["serve"],
        signature_def_map={
            'serving_default': tf.saved_model.signature_def_utils.predict_signature_def(
                {'input': g.get_tensor_by_name('input_image_as_bytes:0')},
                {
                    'prediction': g.get_tensor_by_name('prediction:0'),
                    'probability': g.get_tensor_by_name('probability:0')
                }
            ),
        },
        clear_devices=True
    )

builder.save()
```

**Comment by ckirmse** [comment]
Thanks a **lot** for posting this--I'll test it tonight if possible (similar to @emedvedev this is just a side project for me) and l'll post back results.

**Comment by ckirmse** [comment]
OK, I tested your export (after tweaking to include 'prediction') and it came out the same as the export that @emedvedev added, meaning same file size and predictions came out the same (which for me is a lot worse than when using the 'test' function of the main repo). I suspect the difference I'm seeing is due to the settings I'm using:

` --full-ascii --max-width 380 --max-height 32 --max-prediction 60`

Maybe the large max-width (or max prediction length) is related? I'm guessing you guys are doing very short texts, but I'm trying to read full sentences in some cases.

**Comment by emedvedev** [comment]
@ckirmse I'm not sure what could be the difference between the `test` function and the exported model, but as a hunch, can you change the first three symbols of the charmap from `['', '', '']` to `['<GO>', '<EOS>', '<PAD>']` and then see if the gibberish you're seeing actually comes after `<EOS>`? It's possible that it's just not cut properly.

**Comment by ckirmse** [comment]
I ran some tests today--I've been creating the model on a linux machine, and running inferences on a macos machine when I've seen this problem. I just had the same problem on the macos machine when using the new "predict" mode, so the problem appears to be running the model on a different setup (not sure why os would matter, but between tensorflow and the various dependencies, it's hard to isolate the root cause), and not exporting the model. I suspect the tensorflow serving setup would work fine.

**Comment by emedvedev** [comment]
@ckirmse what's the CPU/GPU setup between machines? The problem may appear because some Tensorflow operations are non-deterministic on GPUs, and the results may be different because of that. Usually they are only slightly different though, and it doesn't give a significant deviation, but could still happen.

A more obvious guess would be the Tensorflow version.

**Comment by ckirmse** [comment]
I have a GPU on the linux box, just CPU on macOS. Both of them have TensorFlow 1.3. I'm working on training with a larger batch of synthesized data and will run more tests across machines once I get good enough results on at least one machine :). I think it's close.

**Comment by tumusudheer** [comment]
Hi @emedvedev ,

I'm facing the same issue as the frozen model (using the code provided in the branch) is not giving good results (not as same as when you ran test). I'm getting good results when I ran 'test' on the same image. So I've decided to initialize the model as you were doing [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/__main__.py#L247) and save as binary graph (without weights). Later I used tensorflow's freeze_graph utility with the save binary graph and checkpoint as inputs.

With the frozen graph generated using tensorflow's freeze_graph utility is giving good results (Same word as test). Each time I ran the inference using this frozen graph on the same input image, I'm getting same word as output but the probabilities are changing (every time). Any issue with the output tensor (probability) that you know of?

**Comment by mattfeury** [comment]
after looking at #34, i've started to dig a little deeper and it does look like i'm also seeing some inconsistency, both on the probability and the predicted text when using my exported model. i'm going to dig in a little more here today, but i'm running them both on the same machine so should be same hardware and seeing a lot of inconsistency.
