### ISSUE TITLE
Synth 90k training error

### ISSUE THREAD

**Issue by antoniosimunovic** [emedvedev/attention-ocr#3]
Hi,

I'm trying to train model on a Synth90k and I run into this error during training:

`InvalidArgumentError (see above for traceback): TensorArray has inconsistent shapes.  Index 0 has shape: [31,135,1] but index 1 has shape: [31,81,1]
	 [[Node: map/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@map/TensorArray_1"], dtype=DT_UINT8, element_shape=[?,?,1], _device="/job:localhost/replica:0/task:0/cpu:0"](map/TensorArray_1, map/TensorArrayStack/range, map/while/Exit_1/_115)]]
	 [[Node: cond_52/strided_slice/_409 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_44518_cond_52/strided_slice", tensor_type=DT_STRING, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
`

Does training script expects all input images to be of same width?

**Comment by emedvedev** [comment]
Yes, currently all the images are supposed to be the same size. I'm planning to fix that in future versions, but unfortunately it's a limitation for now. You can modify the dataset generator so that it would pad all the images though: it shouldn't increase size too much and the accuracy might not suffer a lot (if at all).

**Comment by emedvedev** [comment]
Just released a new version that should pad all the images to maximum width and height. You can use the following parameters in the CLI (with your own values, of course): `--max-width=200 --max-height=120 --max-prediction=15`.

**Comment by antoniosimunovic** [comment]
Thank you, I've started the training process with new version.
