### ISSUE TITLE
how to use this module?

### ISSUE THREAD

**Issue by CruzzRazor** [emedvedev/attention-ocr#44]
how can i use this package in my code? 
when i use that aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords line it shows command not found.
what to do after pip install aocr?
is there any tutorial available ?

**Comment by emedvedev** [comment]
If you need anything other than the [README](https://github.com/emedvedev/attention-ocr/blob/master/README.md), then I can only suggest to check out the source code. For general Tensorflow tutorials, the Tensorflow website is very helpful.
