### ISSUE TITLE
How to use 'predict' ?

### ISSUE THREAD

**Issue by 0x0004** [emedvedev/attention-ocr#45]
I see the'predict' in modle.py.
so, running command: aocr predict xx.png ,it said 'open file fail'.
How to use 'predict' ?

**Comment by emedvedev** [comment]
See `[__main__.py](https://github.com/emedvedev/attention-ocr/blob/master/aocr/__main__.py#L312)`: after you've trained the model, you can predict by passing the file list to stdin line by line.
