### ISSUE TITLE
UTF-8 and Special Characters

### ISSUE THREAD

**Issue by AdamWP** [emedvedev/attention-ocr#52]
I'm trying to train with special characters such as currency symbols, hyphens, slashes, and apostrophes.  I see that data_gen.py sets the character map to ascii.  Is this project limited to ascii characters for any particular reason or should it be possible to use UTF-8 characters?

**Comment by emedvedev** [comment]
It's absolutely not limited for ASCII characters, and should work just fine with a larger charset. `[CHARMAP](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/data_gen.py#L14)` should be the only thing you'd need to modify for that. It shouldn't even affect performance too much, but I'm not 100% sure. 

I'd really appreciate it if you could report your findings once you modify the model to use a larger charset!

**Comment by AdamWP** [comment]
I added the special characters I needed, but I also had to add 

#!/usr/bin/env python
# -*- coding: utf-8 -*-

to the top of data_gen.py.        It looks like training is working so far.  I'll let you know how it goes.

Lines 17 & 18 look like they may cause issues, or am I mistaken?

def setFullAsciiCharmap():
        DataGen.CHARMAP = ['', '', ''] + [chr(i) for i in range(32, 127)]

**Comment by emedvedev** [comment]
It's only called when the `full-ascii` flag is specified (for case-sensitive recognition), so shouldn't really interfere with your modifications.

**Comment by AdamWP** [comment]
Thanks.  It worked!
