### ISSUE TITLE
ValueError: GraphDef cannot be larger than 2GB

### ISSUE THREAD

**Issue by feygina** [emedvedev/attention-ocr#53]
I'm training on my own dataset containing rather long text lines. I'm wondering if it can be the reason for this error. Probably anyone can know how to fix it? Thanks!

**Comment by emedvedev** [comment]
Long lines are, indeed, the problem: when you set a high `max-prediction` value for longer text, it significantly increases the number of seq2seq encoder/decoder nodes, so the graph size bloats. The title error aside, it might result in pretty bad performance; this model isn't optimized for something like that, unfortunately.

You could try extracting individual words from your image first (or at least splitting the lines into smaller chunks) through segmentation. OpenCV would be a good library to look at if words on your images have well-defined boundaries.

[Reading Text in the Wild](http://www.robots.ox.ac.uk/~vgg/research/text/) is a good example of _text spotting_ if your images are a bit more complex.

Finally, if you're just looking for a good OCR library for scanned text, try [Tesseract](https://github.com/tesseract-ocr/tesseract).

Good luck!

**Comment by feygina** [comment]
Thank you for your response and advice. I tried Tesseract before, and it gave me only 55% accuracy (I have low resolution images), but Google Vision API OCR 87%. So now I want to train something that can perform like Google or even better.

**Comment by emedvedev** [comment]
You can certainly try this model then, but you'll still have to split your strings into shorter segments, or maybe even add an object detection layer to the model, although that'd be a lot of work, and I'm not sure about its results for OCR. Let me know how it goes though, I'm curious now!

**Comment by kamalkarki** [comment]
@feygina 
I am also struck here to improve the accuracy as I am working on the scanned documents for the text retrieval. I have also tried " tesseract " and some other tools.
Can you suggest anything in which direction to think/explore?
