### ISSUE TITLE
Questions about spaces

### ISSUE THREAD

**Issue by AdamWP** [emedvedev/attention-ocr#54]
The datasets I've seen referenced for this project all contain single strings of text that contain no spaces .  My use case will require identifying strings of text that contain spaces.   How well does attention-ocr work if it is provided an image that contains multiple strings of text separated by spaces?  Will it work, or does it require images with continuous strings of text only?

**Comment by emedvedev** [comment]
It might work, given the strings aren't too long. Otherwise you could try some preprocessing / segmentation beforehand (see https://github.com/emedvedev/attention-ocr/issues/53).

**Comment by AdamWP** [comment]
I'll give it a try. Thanks!

**Comment by ckirmse** [comment]
I've been detecting strings with spaces very successfully, so you should be fine @AdamWP .

**Comment by AdamWP** [comment]
Thanks @ckirmse !  That's what I like to hear 👍 .   Did you train your model with strings of text that included spaces, or continuous strings of text?

**Comment by ckirmse** [comment]
I trained it with maybe 1/2 strings with spaces, 1/2 without. In general the more similar the training data to the evaluation data the better.
