### ISSUE TITLE
Finishing the training and saving the model at step 0.

### ISSUE THREAD

**Issue by ccnankai** [emedvedev/attention-ocr#57]
.

**Comment by ccnankai** [comment]
@mattfeury @ckirmse

**Comment by emedvedev** [comment]
Hi! Try debugging the `.gen` method [around L50-L51](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/data_gen.py#L50-L51). Could be something with `make_one_shot_iterator`, but I'm not entirely sure.

**Comment by ccnankai** [comment]
@emedvedev 
After I git clone  the project, Python __main__.py  train dataset_path=data.tfrecords  --batch-size=1
![image](https://user-images.githubusercontent.com/33537489/35289125-6b4c06ac-00a1-11e8-8736-401e67e67005.png)
Even if I change the path of datasets ,  This error will be displayed.thank you for your help

**Comment by emedvedev** [comment]
It should be `train data.tfrecords` rather than `train dataset_path=data.tfrecords`

**Comment by ccnankai** [comment]
@emedvedev   I did not find where the error occurred(stop at step 0 ), the code in L50-L51  looks lilke correct.
![2018-01-24 11 15 19](https://user-images.githubusercontent.com/33537489/35312727-eb64a280-00f7-11e8-9c7e-d0a68ed8ed11.png)
thank you !
