### ISSUE TITLE
Detecting multiple words?

### ISSUE THREAD

**Issue by Omnipresent** [emedvedev/attention-ocr#59]
I've read the original paper and it seems that it detects multiple words in an image. I would like to confirm whether this is true? By multiple words I mean detecting text "The Mistake You" in the image below:

![box_0](https://user-images.githubusercontent.com/115446/35489196-98ad6244-0461-11e8-8075-8c54bc1f9e3a.jpg)

Also, Is there a saved model available that is trained on http://www.robots.ox.ac.uk/~vgg/data/text/ ? If not, if I train the model on that dataset which contains single words (not multiple words), will the model work on the images like the above example? 

I've tried the above image in CRNN (https://arxiv.org/abs/1507.05717) but it doesn't recognize the text well because of the spaces.

**Comment by ckirmse** [comment]
If you train it with data that includes spaces then it will detect multiple words, but the training is key to making that work. That dataset above appears to only include single words so you'd have to enhance that.
