### ISSUE TITLE
Optimizing for Inference

### ISSUE THREAD

**Issue by AdamWP** [emedvedev/attention-ocr#66]
I'm trying to run my graph on an Android device however I'm having some issues optimizing the graph.   Has anyone managed to get attention-ocr to work on an android devices?   Here's what I've tried so far.

I froze the graph using aocr export --format=frozengraph ./exported-model

Then I tried the optimizing for inference by running:

>$ python optimize_for_inference.py --input frozen_graph.pb --output graph_optimized.pb --input_names=input_image_as_bytes --output_names=prediction,probability`

The resulting .pb file gave me an error.

> Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Node 'cond_1/strided_slice/stack': Control dependencies must come after regular dependencies

I then tried optimizing for deployment with the newer graph_transforms by running:

> $ bazel build tensorflow/tools/graph_transforms:transform_graph
> 
> $ bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=frozen_graph.pb --out_graph=optimized.pb --inputs='input_image_as_bytes' --outputs='prediction,probability' --transforms=' strip_unused_nodes(type=float, shape="1,299,299,3") fold_constants(ignore_errors=true) fold_batch_norms fold_old_batch_norms'

That gave me another error.

> Node 'model_with_buckets/embedding_attention_decoder/embedding_lookup' expects to be colocated with unknown node 'embedding_attention_decoder/embedding'

**Comment by reidjohnson** [comment]
I can't speak to your specific issues, but I have a modified version of the model that I've been testing on iOS and Android (replacing the respective TensorFlow demo apps with the model) and can describe what I did.

To get the model running on-device with minimal effort, I had to change the definition of the input data to `self.img_data = tf.placeholder(tf.float32, [1, DataGen.IMAGE_HEIGHT, DataGen.IMAGE_WIDTH, 1], name='input')`. This removes the image preprocessing from the graph and changes the placeholder type to a float with predefined height and width. I then froze the graph the same way you did.

I'll note that even after this, I had to modify the TensorFlow source code to include string operations (e.g., `tf.string_split`) and to register additional operations for mobile. I can provide more specific guidance if you run into similar issues while building the app.

**Comment by AdamWP** [comment]
Thanks @reidjohnson .   Does this require that all images in the dataset must have the same height and width?

**Comment by reidjohnson** [comment]
No, only that they're resized/padded to a fixed height and width (as already performed by the current code).

**Comment by reidjohnson** [comment]
Also note that the TensorFlow Android and iOS examples perform similar resizing.

**Comment by noob-ja** [comment]
hi @reidjohnson 
isit possible for you to outline the steps to enable running on android?
currently it keeps giving me error

> E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input_image_as_bytes], outputs:[prediction, probability]
E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                  Process: com.example.localuser.attention_ocr, PID: 17872
                  java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
                    device='GPU'; T in [DT_RESOURCE]
                    device='GPU'; T in [DT_STRING]
                    device='GPU'; T in [DT_BOOL]
                    device='GPU'; T in [DT_INT32]
                    device='GPU'; T in [DT_FLOAT]
                    device='CPU'; T in [DT_BOOL]
                    device='CPU'; T in [DT_FLOAT]
                    device='CPU'; T in [DT_INT32]
                  	 [[Node: 9 = Switch[T=DT_STRING](input_image_as_bytes:0, 7)]]
                      at org.tensorflow.Session.run(Native Method)
                      at org.tensorflow.Session.access$100(Session.java:48)
                      at org.tensorflow.Session$Runner.runHelper(Session.java:298)
                      at org.tensorflow.Session$Runner.run(Session.java:248)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
                      at com.example.localuser.attention_ocr.MainActivity$1$2.run(MainActivity.java:97)
                      at java.lang.Thread.run(Thread.java:784)

**Comment by abucka** [comment]
> I can't speak to your specific issues, but I have a modified version of the model that I've been testing on iOS and Android (replacing the respective TensorFlow demo apps with the model) and can describe what I did.
> 
> To get the model running on-device with minimal effort, I had to change the definition of the input data to `self.img_data = tf.placeholder(tf.float32, [1, DataGen.IMAGE_HEIGHT, DataGen.IMAGE_WIDTH, 1], name='input')`. This removes the image preprocessing from the graph and changes the placeholder type to a float with predefined height and width. I then froze the graph the same way you did.
> 
> I'll note that even after this, I had to modify the TensorFlow source code to include string operations (e.g., `tf.string_split`) and to register additional operations for mobile. I can provide more specific guidance if you run into similar issues while building the app.

Hallo @reidjohnson, could you please share the code that you had to modify in order to feed the input data as float? I would be really interested in your solution. 
I would like to export the model to SavedModel format but in the export.py script you can only do it with input image as bytes. I would like to pass an uint8 image (or float) to the model if possible.

**Comment by reidjohnson** [comment]
Hey @abucka, I haven't worked on this project in some time and have to go off of memory. But, when freezing the graph, I believe I defined the placeholder code [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L116) using the snippet above, also making sure to change the name of the tensor [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/export.py#L24) to `input:0` (to match the snippet above).
