### ISSUE TITLE
No bias terms in the CNN

### ISSUE THREAD

**Issue by MBleeker** [emedvedev/attention-ocr#70]
Is there a reason why the feature extraction is only using convolutional kernels and no bias term?

**Comment by emedvedev** [comment]
Not that I remember, but feel free to ask the [original authors of the model](https://github.com/da03/Attention-OCR) or just experiment and submit a PR if you get better results with bias terms.

**Comment by MBleeker** [comment]
Hi,

I looked into this question and I found the answer. When applying  batch norm you do not need the bias terms.  Batch norm will recenter the feature map such that bias terms are not needed.

Cheers
