### ISSUE TITLE
How to set GPU ID when training？

### ISSUE THREAD

**Issue by lmolhw5252** [emedvedev/attention-ocr#72]
I use command:
aocr  xxx.tfrecords --gpu-id=0
it doesn't work.

**Comment by emedvedev** [comment]
Well, your GPU ID flag seems to be correct. Can you paste the full command and its output?

**Comment by lmolhw5252** [comment]
aocr: error: unrecognized arguments: --gpu-id=1

**Comment by emedvedev** [comment]
@lmolhw5252 if `aocr xxx.tfrecords --gpu-id=0` is the exact way you're entering the command (I can't tell without the full output), then you're missing a subcommand: `train`, `test`, etc.

If the subcommand is there, please paste the _full_ command and the output from the console.

**Comment by lmolhw5252** [comment]
oh, sorry, the full command is:
aocr train xxx.tfrecords --gpu-id=1
return: usage: aocr [-h] [--log-path LOG_PATH] []
                       [][][][]
                        {dataset, train, test, export, predict}...
aocr:error: unrecognized arguments: --gpu-id=1

**Comment by lmolhw5252** [comment]
![image](https://user-images.githubusercontent.com/20182607/37576034-19b5091c-2b65-11e8-9038-8370d4eea6f2.png)

**Comment by emedvedev** [comment]
Can you try `aocr --gpu-id=1 train xxx.tfrecords`? The flag order matters in `argparse`, unfortunately. If that doesn't work either, I'll take a closer look tomorrow.

**Comment by lmolhw5252** [comment]
ok, I will try it, and reply you.Thanks a lot!

**Comment by lmolhw5252** [comment]
Hi I got a problem about tf.AUTO_REUSE, when I use tensorflow 1.3 , I got the problem of 
![image](https://user-images.githubusercontent.com/20182607/37637726-4e387fe0-2c44-11e8-9351-e75784ace83b.png)

**Comment by emedvedev** [comment]
Glad the flag is working for you now! `tf.AUTO_REUSE` doesn't exist in 1.3, so you'd need to update your TensorFlow.

On a related note, the traceback doesn't look anything like the code in `master`: `AUTO_REUSE` isn't used anywhere in `aocr`, and there's no `util/layers.py`, too. If you're running some kind of fork or a modified version, you should really open an issue there: it's hard for me to debug issues with a completely different codebase.

**Comment by lmolhw5252** [comment]
When  i using tf 1.4 I got 
![image](https://user-images.githubusercontent.com/20182607/37638416-c0470392-2c47-11e8-834c-ddc51c47a5ae.png)

**Comment by emedvedev** [comment]
Well, it tells you that your dataset file does not exist. Check your path more carefully, it's probable that there's just a typo there somewhere.

I'm going to close the issue as the original problem is resolved, but if you have any more problems with the codebase in `master` (_not_ a modification or a fork), please feel free to open a new one!
