### ISSUE TITLE
Whole line (multiple words) recognition

### ISSUE THREAD

**Issue by hiepph** [emedvedev/attention-ocr#76]
Refer this issue https://github.com/emedvedev/attention-ocr/issues/59, are some modifications I make below sufficient to recognize multiple words (as a line)?

+ Include the space character into `CHARMAP` in `aocr/util/data_gen.py`.

+ Increase `max-prediction` for predicted phrase.

+ Increase `max-width` for input image

**Comment by emedvedev** [comment]
Should be enough, I think.

**Comment by ckirmse** [comment]
Yes that's why --full-ascii exists too, @hiepph . I've done this successfully.

**Comment by ckirmse** [comment]
Hi @hiepph --sorry I didn't see this message sooner. I'm using max-width 380, max-height 32, max-prediction 75 with a few tens of thousands of images. You don't want max-height to be so large because all the images will get stretched to that size, and it will destroy the aspect ratio. You should be able to see some results with only 1000 images for training, but you need a lot more to get really good results I believe.

**Comment by ckirmse** [comment]
Sorry yes you're right, they won't get stretched, but they will be scaled to fit the max-width x max-height rectangle, and if your images are of vastly different aspect ratios then that could reduce quality. In general I think you want max_width to be much larger than max_height, particularly when trying to detect longer strings.

**Comment by hiepph** [comment]
Thank @ckirmse for sharing your configuration. I wouldn't succeed without your help. 

As mine using max-width 500, max-height 160, max-prediction 30 (for name data with 3 to 4 words), with 17.500 train images I gained 93% accuracy for 4300 test images. 

Will close the issue for now.

**Comment by AnhHC** [comment]
Hello @hiepph can help me on multiple words recognition, I followed your guide to make change on max-width, max-height, max-prediction but still can't recognize multiple words.

Thanks,

**Comment by hiepph** [comment]
Hi @AnhHC it's been a while since the last time I used this repo. Are you sure you followed these modifications:

```
+ Include the space character into CHARMAP in aocr/util/data_gen.py.
+ Increase max-prediction for predicted phrase.
+ Increase max-width for input image
```

And the second thing you should check is the size of your dataset. It should have more than 5k of train images.

**Comment by AnhHC** [comment]
Thanks @hiepph , I followed the guidance from you and #54 to train and it can recognize the words on 1 line image now. Btw can it be done with the multi-line word recognition in image @hiepph ?

**Comment by hiepph** [comment]
I don't think it's possible with this network, instead you should separate lines first and then do line recognition.
