### ISSUE TITLE
Can you explain how the accuracy is calculated?

### ISSUE THREAD

**Issue by lmolhw5252** [emedvedev/attention-ocr#79]
When I testing use my model with your code, get the acc is 87%, but I check the file about the result, the correct words are 450 and the incorrect words are 141. So I want to ask about the way to calculate about accuracy.

**Comment by emedvedev** [comment]
Accuracy is calculated using Levenshtein distance to take into account how far off the prediction is.

In other words, let’s say you have ten-character strings, and none of them are predicted correctly, but in all cases 9 out of 10 characters are right. Then you’ll get the accuracy report of 90%.

If you want to count incorrect results as 0% (no matter how much is predicted correctly inside a word), use the `--no-distance` flag.

**Comment by lmolhw5252** [comment]
ok，Thanks a lot

**Comment by lmolhw5252** [comment]
And I got another question about different image size， I see your code use one bucket, does it's mean that the different size of the image will be resized to a fixed size? If I want to use few buckets like /da03/Attention-OCR/ issues, How should I change the code?

**Comment by emedvedev** [comment]
It will be padded rather than resized, so in theory, there should be no decrease in accuracy without the buckets with the same `max-image-width`; there's a decrease in performance, but only if your images are very different in width (because they'd be put into smaller buckets in this case). Changing the code to use buckets now would really be non-trivial.

**Comment by lmolhw5252** [comment]
Ok, I got it. Thank you for your reply!

**Comment by emedvedev** [comment]
You're welcome! I'll close this issue, but if you have more questions, feel free to open additional ones.

**Comment by kulkarnivishal** [comment]
Don't think your interpretation of accuracy is right. Since replacements are also counted in Levenshtein distance, if 9 predicted characters are not correct with respect to position, it would give 0%. For example with distance accuracy for "have" and "evah" would be 0%
