### ISSUE TITLE
Can I set different learning_rate in different layer?

### ISSUE THREAD

**Issue by lmolhw5252** [emedvedev/attention-ocr#85]
How Can I set different learning_rate in the different layer?

**Comment by lmolhw5252** [comment]
Looking for your reply! Thankyou

**Comment by emedvedev** [comment]
Hi! I'm afraid you can't do that using the CLI, because the model just isn't suited for this. :(

If you decide to fork the model and modify the source code, please let me know what kind of results you'll end up getting!
