### ISSUE TITLE
Usage with tensorflow_model_server

### ISSUE THREAD

**Issue by pokonski** [emedvedev/attention-ocr#93]
Hi!

I have successfully trained and exported the model but failing to serve it via HTTP REST API (https://www.tensorflow.org/serving/api_rest)

I am guessing it's because of an invalid format of inputs or structure. The documentation suggests to encode binary files as base64. Using: 

```
$ saved_model_cli show --dir ./exported-model/1 --tag_set=serve --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_STRING
        shape: unknown_rank
        name: input_image_as_bytes:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_STRING
        shape: unknown_rank
        name: prediction:0
    outputs['probability'] tensor_info:
        dtype: DT_DOUBLE
        shape: unknown_rank
        name: probability:0
  Method name is: tensorflow/serving/predict
```

I know that the input name is `input_image_as_bytes`, but this results in a very cryptic error: "Bad string":

![image](https://user-images.githubusercontent.com/135402/41477079-924c1944-70c3-11e8-9b27-ef462f2cbbd6.png)

(screenshot from Postman tool)

Is it an issue with my incorrect passing of inputs?

**Comment by pokonski** [comment]
Closing as it was an issue with Postman not parsing the response correctly.

Proper payload should look like this:

```json
{
  "signature_name": "serving_default",
  "instances": [
     { "b64": "/9j/4AAQSkZJ=" }
   ]
}
```

**Comment by emedvedev** [comment]
Glad you manage to resolve it! Sorry I couldn’t get back to you on time :)

I would really appreciate it if you could submit an example to the README, btw! Pretty sure other people would find it useful.

**Comment by pokonski** [comment]
@emedvedev will do! Actually have a different issue that could definitely use your expertise, I'll meanwhile prepare a PR to provide this example since REST API is very new.
