### ISSUE TITLE
which paper of the implemation of the code is about ?

### ISSUE THREAD

**Issue by lovebobo** [emedvedev/attention-ocr#97]

**Comment by lovebobo** [comment]
aha, I want to know the code of "attention-ocr" is about which paper.

**Comment by emedvedev** [comment]
Ah! Well, it’s not “about a paper,” it’s meant for practical applications. However, it’s based (loosely at this point) on https://github.com/da03/Attention-OCR, so you could ask its authors the same question, because that model was created for academic research IIRC.

**Comment by kulkarnivishal** [comment]
i think this: https://arxiv.org/abs/1609.04938v1
